### ISSUE TITLE
New ghosts

### ISSUE THREAD

**Issue by Celeo** [un0btanium/phasmophobia-cheatsheet#1]
Thanks for the app!

There are [2 new ghost types](https://trello.com/b/9QrnqQ1j/phasmophobia) coming soon to beta:

## Yokai

A Yokai is a common type of ghost that is attracted to human voices. They can usually be found haunting family homes.

Unique Strengths: Talking near a Yokai will anger it and increase it's chance of attacking.

Weaknesses: When hunting a Yokai can only hear voices close to it.

Evidence: Spirit Box, Ghost Orb and Ghost Writing.

## Hantu

A Hantu is a rare ghost that can be found in hot climates. They are known to attack often during cold weather.

Unique Strengths: Lower temperatures can cause the Hantu to move at faster speeds.

Weaknesses: A Hantu will move slower in warmer areas.

Evidence: Fingerprints, Ghost Orb and Ghost Writing.

---

1. Do you want me to raise a PR to add them?
1. Do you want to wait until:
    1. they're added to beta, or
    1. they're added to live?

**Comment by un0btanium** [comment]
Thank you for letting me know. I quickly added them. Feel free to notify me in case of more updates as I am currently not keeping up with the game and its updates.

**Comment by Celeo** [comment]
Excellent, thank you!
