### ISSUE TITLE
Wrong second evidence for Hantu

### ISSUE THREAD

**Issue by I3lackRacer** [un0btanium/phasmophobia-cheatsheet#11]
In the Journal, the Hantu is described a ghost who is running faster at colder speeds, but in the cheat sheet it's the other way. 
Please fix. Thanks. :) 
![image](https://user-images.githubusercontent.com/14124721/144731295-3eeeccf3-ce81-4f9f-9e2d-9f948f88afe3.png)
![image](https://user-images.githubusercontent.com/14124721/144731301-aa827592-e82d-4df9-9fc7-d82e6b1537fa.png)

**Comment by BotiKis** [comment]
Fixed with the latest udpate - Thank you!
