### ISSUE TITLE
Add Ghost Orb Evidence to Mimic

### ISSUE THREAD

**Issue by Redforce04** [un0btanium/phasmophobia-cheatsheet#15]
We may want to add ghost orbs to the evidence for the mimic, as it could throw off newer players who are unaware of the feature. @un0btanium @BotiKis Thoughts on this idea? Technically it is correct to include it as evidence. I will create a pr later if I have time.

**Comment by BotiKis** [comment]
I didn't know that having more than primary 3 evidences is possible in the cheatsheet. Yes it makes sense - let's do that.
Still leave a note in form of a secondary evidence that explains it. [Nuzzgard](https://www.youtube.com/watch?v=eQK8ZsF69Po&) released an updated guide which I will compare to our data and complete it.

**Comment by un0btanium** [comment]
Sure, sounds good.

**Comment by Redforce04** [comment]
@BotiKis I used the wiki for the data on the mimic, but feel free to cross check info as the wiki is not always perfect with new updates. Anyways PR #16 is ready, and tested.

**Comment by BotiKis** [comment]
@Redforce04 All valid!
I also don't necessarily trust the wiki and always wait for reasearch by players (insym, psycho and nuzz) or dev let's plays where they chat about stuff. And of course the patchnotes - when they are not vague ;).
