### ISSUE TITLE
[Suggestion] Allow for secondary evidence with 1 primary

### ISSUE THREAD

**Issue by Master-Guy** [un0btanium/phasmophobia-cheatsheet#26]
At this moment the secondary evidence doesn't show unless you enable the checkmark to always show everything, or unless you have selected two primary evidences. A personal preference would be to show all secondary evidence even with only 1 primary selected.

**Comment by un0btanium** [comment]
Added!

**Comment by Master-Guy** [comment]
Thanks, works great!
